/**
 * @author Virtusa
 */
package org.bian.service;

import java.util.List;

import org.bian.dto.*;

public interface ItStandardsAndGuidelinesApiService {

	SDITStandardsAndGuidelinesActivateOutputModel activate(SDITStandardsAndGuidelinesActivateInputModel request);
	
	BQDevelopmentToolingandEnvironmentCaptureOutputModel captureDevelopmenttoolingandenvironment(String sdReferenceId, String crReferenceId, String bqReferenceId, BQDevelopmentToolingandEnvironmentCaptureInputModel request);
	
	BQITPoliciesandGuidelinesCaptureOutputModel captureItpoliciesandguidelines(String sdReferenceId, String crReferenceId, String bqReferenceId, BQITPoliciesandGuidelinesCaptureInputModel request);
	
	BQProductTestingandDeploymentMechanismsCaptureOutputModel captureProducttestinganddeploymentmechanisms(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductTestingandDeploymentMechanismsCaptureInputModel request);
	
	BQProductionEnvironmentandSupportServicesCaptureOutputModel captureProductionenvironmentandsupportservices(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductionEnvironmentandSupportServicesCaptureInputModel request);
	
	BQProductionPlatformsandInfrastructureCaptureOutputModel captureProductionplatformsandinfrastructure(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductionPlatformsandInfrastructureCaptureInputModel request);
	
	CRTechnologyStandardsSpecificationCaptureOutputModel capture(String sdReferenceId, String crReferenceId, CRTechnologyStandardsSpecificationCaptureInputModel request);
	
	SDITStandardsAndGuidelinesConfigureOutputModel configure(String sdReferenceId, SDITStandardsAndGuidelinesConfigureInputModel request);
	
	CRTechnologyStandardsSpecificationControlOutputModel control(String sdReferenceId, String crReferenceId, CRTechnologyStandardsSpecificationControlInputModel request);
	
	BQDevelopmentToolingandEnvironmentExchangeOutputModel exchangeDevelopmenttoolingandenvironment(String sdReferenceId, String crReferenceId, String bqReferenceId, BQDevelopmentToolingandEnvironmentExchangeInputModel request);
	
	BQITPoliciesandGuidelinesExchangeOutputModel exchangeItpoliciesandguidelines(String sdReferenceId, String crReferenceId, String bqReferenceId, BQITPoliciesandGuidelinesExchangeInputModel request);
	
	BQProductTestingandDeploymentMechanismsExchangeOutputModel exchangeProducttestinganddeploymentmechanisms(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductTestingandDeploymentMechanismsExchangeInputModel request);
	
	BQProductionEnvironmentandSupportServicesExchangeOutputModel exchangeProductionenvironmentandsupportservices(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductionEnvironmentandSupportServicesExchangeInputModel request);
	
	BQProductionPlatformsandInfrastructureExchangeOutputModel exchangeProductionplatformsandinfrastructure(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductionPlatformsandInfrastructureExchangeInputModel request);
	
	CRTechnologyStandardsSpecificationExchangeOutputModel exchange(String sdReferenceId, String crReferenceId, CRTechnologyStandardsSpecificationExchangeInputModel request);
	
	SDITStandardsAndGuidelinesFeedbackOutputModel feedback(String sdReferenceId, SDITStandardsAndGuidelinesFeedbackInputModel request);
	
	CRTechnologyStandardsSpecificationInitiateOutputModel initiate(String sdReferenceId, CRTechnologyStandardsSpecificationInitiateInputModel request);
	
	BQDevelopmentToolingandEnvironmentInitiateOutputModel initiateDevelopmenttoolingandenvironment(String sdReferenceId, String crReferenceId, BQDevelopmentToolingandEnvironmentInitiateInputModel request);
	
	BQITPoliciesandGuidelinesInitiateOutputModel initiateItpoliciesandguidelines(String sdReferenceId, String crReferenceId, BQITPoliciesandGuidelinesInitiateInputModel request);
	
	BQProductTestingandDeploymentMechanismsInitiateOutputModel initiateProducttestinganddeploymentmechanisms(String sdReferenceId, String crReferenceId, BQProductTestingandDeploymentMechanismsInitiateInputModel request);
	
	BQProductionEnvironmentandSupportServicesInitiateOutputModel initiateProductionenvironmentandsupportservices(String sdReferenceId, String crReferenceId, BQProductionEnvironmentandSupportServicesInitiateInputModel request);
	
	BQProductionPlatformsandInfrastructureInitiateOutputModel initiateProductionplatformsandinfrastructure(String sdReferenceId, String crReferenceId, BQProductionPlatformsandInfrastructureInitiateInputModel request);
	
	BQDevelopmentToolingandEnvironmentRequestOutputModel requestDevelopmenttoolingandenvironment(String sdReferenceId, String crReferenceId, String bqReferenceId, BQDevelopmentToolingandEnvironmentRequestInputModel request);
	
	BQITPoliciesandGuidelinesRequestOutputModel requestItpoliciesandguidelines(String sdReferenceId, String crReferenceId, String bqReferenceId, BQITPoliciesandGuidelinesRequestInputModel request);
	
	BQProductTestingandDeploymentMechanismsRequestOutputModel requestProducttestinganddeploymentmechanisms(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductTestingandDeploymentMechanismsRequestInputModel request);
	
	BQProductionEnvironmentandSupportServicesRequestOutputModel requestProductionenvironmentandsupportservices(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductionEnvironmentandSupportServicesRequestInputModel request);
	
	BQProductionPlatformsandInfrastructureRequestOutputModel requestProductionplatformsandinfrastructure(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductionPlatformsandInfrastructureRequestInputModel request);
	
	CRTechnologyStandardsSpecificationRequestOutputModel request(String sdReferenceId, String crReferenceId, CRTechnologyStandardsSpecificationRequestInputModel request);
	
	CRTechnologyStandardsSpecificationRetrieveOutputModel retrieve(String sdReferenceId, String crReferenceId);
	
	List<String> retrieveBQIds(String sdReferenceId, String crReferenceId, String behaviorQualifier);
	
	List<String> retrieveBQs();
	
	List<String> retrieveRefIds(String sdReferenceId);
	
	SDITStandardsAndGuidelinesRetrieveOutputModel retrieveSD(String sdReferenceId);
	
	BQDevelopmentToolingandEnvironmentRetrieveOutputModel retrieveDevelopmenttoolingandenvironment(String sdReferenceId, String crReferenceId, String bqReferenceId);
	
	BQITPoliciesandGuidelinesRetrieveOutputModel retrieveItpoliciesandguidelines(String sdReferenceId, String crReferenceId, String bqReferenceId);
	
	BQProductTestingandDeploymentMechanismsRetrieveOutputModel retrieveProducttestinganddeploymentmechanisms(String sdReferenceId, String crReferenceId, String bqReferenceId);
	
	BQProductionEnvironmentandSupportServicesRetrieveOutputModel retrieveProductionenvironmentandsupportservices(String sdReferenceId, String crReferenceId, String bqReferenceId);
	
	BQProductionPlatformsandInfrastructureRetrieveOutputModel retrieveProductionplatformsandinfrastructure(String sdReferenceId, String crReferenceId, String bqReferenceId);
	
	CRTechnologyStandardsSpecificationUpdateOutputModel update(String sdReferenceId, String crReferenceId, CRTechnologyStandardsSpecificationUpdateInputModel request);
	
	BQDevelopmentToolingandEnvironmentUpdateOutputModel updateDevelopmenttoolingandenvironment(String sdReferenceId, String crReferenceId, String bqReferenceId, BQDevelopmentToolingandEnvironmentUpdateInputModel request);
	
	BQITPoliciesandGuidelinesUpdateOutputModel updateItpoliciesandguidelines(String sdReferenceId, String crReferenceId, String bqReferenceId, BQITPoliciesandGuidelinesUpdateInputModel request);
	
	BQProductTestingandDeploymentMechanismsUpdateOutputModel updateProducttestinganddeploymentmechanisms(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductTestingandDeploymentMechanismsUpdateInputModel request);
	
	BQProductionEnvironmentandSupportServicesUpdateOutputModel updateProductionenvironmentandsupportservices(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductionEnvironmentandSupportServicesUpdateInputModel request);
	
	BQProductionPlatformsandInfrastructureUpdateOutputModel updateProductionplatformsandinfrastructure(String sdReferenceId, String crReferenceId, String bqReferenceId, BQProductionPlatformsandInfrastructureUpdateInputModel request);
	
}
